### ISSUE TITLE
Confirm design & style

### ISSUE THREAD

**Issue by Stivaros** [HackTheNight/jargonaut#1]
https://gomockingbird.com/projects/pman2yq

Comments/feedback?

**Comment by Bishwin** [comment]
Think this is good. it'll be a solid start to appropriately show what we're selling

**Comment by Stivaros** [comment]
Based on @alectronic0's branch #5, I think it's easier to stick with GOVUK styling for now but using the template above.

**Comment by Stivaros** [comment]
Updated wireframe with hyperlink reference section

**Comment by Stivaros** [comment]
#5 Imported GOVUK styling
